### ISSUE TITLE
TypeError: must be type, not classobj

### ISSUE THREAD

**Issue by ttika** [kinkstruction-admin/imagefapper#1]
Getting a "TypeError: must be type, not classobj" message whenever I run it, any advice?

**Comment by otherthing** [comment]
same here

Traceback (most recent call last):
  File "/usr/local/bin/imagefapper", line 9, in <module>
    load_entry_point('imagefapper==0.3.0', 'console_scripts', 'imagefapper')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 23, in main
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 55, in __init__
AssertionError: Unexpected gallery id: www.imagefap.com
max@max:~/Desktop/.p$ imagefapper
Usage: imagefapper [OPTIONS] URL

Error: Missing argument "url".
max@max:~/Desktop/.p$ imagefapper http://www.imagefap.com/pictures/5925287/Gravity-pull-did-a-good-job
Traceback (most recent call last):
  File "/usr/local/bin/imagefapper", line 9, in <module>
    load_entry_point('imagefapper==0.3.0', 'console_scripts', 'imagefapper')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 25, in main
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 142, in download
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 117, in get_image_links
  File "build/bdist.linux-x86_64/egg/imagefapper/imagefapper.py", line 103, in get_photo_pages
  File "build/bdist.linux-x86_64/egg/imagefapper/scraper.py", line 23, in __init__
TypeError: must be type, not classobj
